In [1]:
def sumofthree (a , b, c) :
    sum = a + b + c
    return sum


In [2]:
sumofthree (3, 4, 5)


12

In [1]:
print ("Der ist sehr gut")

Der ist sehr gut


In [2]:
fermisk_num = 10

In [3]:
fermisk_num

10

In [3]:
'Hi, ich bin Fermisk'

'Hi, ich bin Fermisk'

In [4]:
'Hi. I\'m fermisk'


"Hi. I'm fermisk"

In [5]:
first_name = 'Fermisk'
last_name = 'Saleh'


In [6]:
first_name

'Fermisk'

In [7]:
last_name[4]

'h'

In [ ]:
#When we use the [] we are splicing the string
first_name[0:3] + last_name[0:3]


'FerSal'

In [10]:
last_name[3:-2]

''

In [11]:
last_name[5:2]

''

In [1]:
fruit = 'apple'
fruit.upper()


'APPLE'

In [ ]:
sorted(fruit)



['a', 'e', 'l', 'p', 'p']

In [14]:
len('i want to know how long this sentence is.')

41

In [16]:
# methods are functions that work only for a specific type of data
# like string methods that only work with strings
'my name is fermisk'.upper()


'MY NAME IS FERMISK'

In [17]:
'my name is fermisk'.count('m')


3

In [20]:
'filename.txt'.endswith('.txt')

True

In [21]:
'filename.txt'.endswith('.csv')

False

In [22]:
'my name is Fermisk'.replace(' ', '-')

'my-name-is-Fermisk'

In [ ]:
# changing with format methos. 
# It replaces whatever we want and define inside the format and place it inside the {}
'my first name\'s firs initial is {} and last name first initial is {}'.format(first_name[0], last_name[0])

"my first name's firs initial is F and last name first initial is S"

In [24]:
'my fovorite fruit is {}'.format('avocado')

'my fovorite fruit is avocado'

In [43]:
#f-string
f"my first initials are {first_name[0]}, {last_name[0]}"

'my first initials are F, S'

In [44]:
'FERMISK SALEH'.lower()


'fermisk saleh'

In [ ]:
# type cast term is used when we try to convert a data type to another
int('18')
# the string '18' is type casted into integer
# going from one form to another only happens when the first one represents the other
# i.e the '18' is an integer without the ''

18

In [ ]:
float('8.92')
# '8.92' is a float without the ''

8.92

In [47]:
str(39.8)
# float to string

'39.8'

In [ ]:
# getting user input
age = input("How old are you?")
# a input bar opens on top and asks "how old are you?"
# once you enter the age would be the input number

In [ ]:
age
# I entered 40 when i ran the top command

'40'

In [50]:
colour = input("What is your favourite colour?")
# I will enter green

In [51]:
colour

'Green'

In [53]:
print("you will be", int(age) + 1 , "next year")

you will be 41 next year


In [56]:
# logic operators
# not parameter which makes a boolean return the opposite
not False # to use True or False boolean values, make sure the first letters are caps

True

In [ ]:
not (3 == 3)
# can be used without () because it is an operator and only takes in one operand at a time

False

In [57]:
# and : always checks if the statements on both sides are ture
True and False


False

In [58]:
(9 == 9) and (9 != 7)

True

In [65]:
first_num = input("Enter the first number")
first_num

'3'

In [66]:
second_num = input("Enter the second number")
second_num

'3'

In [68]:
first_num == second_num and True

True

In [ ]:
# And operator will return the first falsy value and the last truthy value if all operands
# are true based on the previous conditions

is_cloudy = 'True'
is_winter = True

is_cloudy and is_winter

True

In [70]:
is_cloudy = 'True'
is_winter = True

is_winter and is_cloudy

'True'

In [ ]:
"" and False # Empty sting and False
# python considers an empty sting as false

''

In [ ]:
False and ""
# a non empty string is considered true by python

False

In [73]:
# python considers 0 as false
0 and 1

0

In [75]:
1 and 0

0

In [76]:
# or operator returns true if just one of the statments is true
False or True

True

In [78]:
(3 != 3) or True

True

In [79]:
('Python' == 'python') or True  # False or true

True

In [80]:
not (7 % 2 == 1) or False  # 7%2=1 (2*3 + 1) is true thus not (7 % 2 == 1) would become false
# false or false

False

In [81]:
# or operator returns the first truthy value  encountered or the last falsy 
# value if all operands are false based on the conditions provided

True or 'True'

True

In [82]:
'True' or True

'True'

In [3]:
year = input("Enter the year")
if int(year) >= 2000:
    print("We are in the 21st century")
else:
    print("we are in the 20th centry")


We are in the 21st century


In [7]:
day_of_week = input('day of the week:')
if (day_of_week == 'Saturday') or (day_of_week == 'Sunday'):
    print('It is weekend')
else:
    print('it is weekday')


it is weekday


In [15]:
# qualifying for an eye exam
def qualified_for_exam (age, qualifying_condition, time_since_last_exam):
    '''assume (1) age is passed as an int for the age of the person, 
    (2) qualifying_condition is passed as boolean indicating whether qualified for an exam 
    (3) time_since_last exam is passed as an int for the number of months since last exam'''
    
    if 0< age <= 19:
        if time_since_last_exam >= 12:
            return "You are eligible for one eye exam and any minor assessment"
        else:
            return "It has not been more than 12 months for another eye exam"
    elif 20 <= age <= 64:
        if qualifying_condition:   #Since it isn't defined, it automatically considers it as true
            if time_since_last_exam >= 12:
                return "You are eligible for one major eye exam and 2 additional follow-up minor assessment"
            else:
                return "It hasn't been 12 months since your last eye exam"
        else:
            return "You do not have a qualifying eligibla medical condition"
    elif age >= 65:
        if time_since_last_exam >= 18:
            return "You are eligible for one major eye exam or two minor assessments"
        else:
            return "It hasn't been 18 months since your last exam"
    else:
        return "Invalid age input"

In [11]:
qualified_for_exam (5, False, 11)


'It has not been more than 12 months for another eye exam'

In [13]:
qualified_for_exam (30, True, 11)


"It hasn't been 12 months since your last eye exam"

In [16]:
qualified_for_exam (0, True, 12)

'Invalid age input'

In [17]:
# Lists, we use [] for lists
vowels = ['a', 'e', 'i', 'o', 'u']
vowels

['a', 'e', 'i', 'o', 'u']

In [19]:
# empty list using conventional method
empt_list = []
empt_list

[]

In [20]:
# another way to creat empty list
empty_list2 = list()
empt_list

[]

In [ ]:
# list of integers
int_list = [1, 4, 3, 6, 6, 6] # can have the same value multiple times
int_list

[1, 4, 3, 6, 6, 6]

In [22]:
# list of ints and characters/variable
var_list = ['w', 2, 4, 5, 'q']
var_list

['w', 2, 4, 5, 'q']

In [23]:
#list within another list
combo_list = [['Sherlock', 'Watson'], [1, 2, 3, 4], 'whatever']
combo_list

[['Sherlock', 'Watson'], [1, 2, 3, 4], 'whatever']

In [ ]:
# ordered: every item in a list can be referenced by its index in the list
# to call multiple items, we use start:end+1
# using -item index, we call from the number to the end i.e. -4 calles an item with index 4 to the end
combo_list[1]

[1, 2, 3, 4]

In [28]:
# to call an item from a list within a list, we use multiple [], 
# the first is from the main, the second from the list within the main list
combo_list[0][1]

'Watson'

In [74]:
# list are mutable whoch means they can be modified in place
# strings, int, floats, bools are immutable
# when we update an immutable data type, we are replacing the value entirely
perfect_square = [1, 4, 9, 16, 25, 36]
perfect_square

[1, 4, 9, 16, 25, 36]

In [30]:
perfect_square[2] = 2
perfect_square

[1, 4, 2, 16]

In [ ]:
# mutable datatype
food_order = ['bread', 'cheese', 'bread']


In [45]:
fermisk_food = food_order

In [43]:
food_order[1] = 'tomato'

In [48]:
food_order

['bread', 'tomato', 'bread']

In [49]:
fermisk_food

['bread', 'tomato', 'bread']

In [53]:
# immutable data type
food_order = 'cheese'

In [54]:
fermisk_food = food_order
fermisk_food

'cheese'

In [55]:
food_order = 'salary'
food_order

'salary'

In [ ]:
# fermisk_ordr will remain the first entery. 
# it won't change regardless of how many time we change the food_order
fermisk_food

'cheese'

In [57]:
a=1
a

1

In [58]:
b=a
b

1

In [59]:
a=2
a

2

In [ ]:
b  # still the first value we enterd for a and b isn't changes because a an int is immutable

1

In [62]:
a = [1,2]
a

[1, 2]

In [63]:
b = a
b

[1, 2]

In [64]:
a[0] = 6
a

[6, 2]

In [66]:
b #since a list is a mutable datatype, the value of b is updated according to changes made to 1

[6, 2]

In [68]:
combo = ['burger', 'fries', 'drink']
kids_meal = list(combo) # created a completely independent copy of a list
combo

['burger', 'fries', 'drink']

In [69]:
kids_meal

['burger', 'fries', 'drink']

In [70]:
combo[0] = 'chicken sandwitch'
combo

['chicken sandwitch', 'fries', 'drink']

In [ ]:
kids_meal # not changed after combo is changed

['burger', 'fries', 'drink']

In [72]:
perfect_square

[1, 4, 2, 16]

In [73]:
len(perfect_square)

4

In [75]:
max(perfect_square)

36

In [ ]:
#syntax objects
sum(perfect_square)

91

In [ ]:
#operators
letters =['a', 'b', 'c']
numbers = [1, 2, 3]
characters = letters + numbers # merges them concatenates?
characters


['a', 'b', 'c', 1, 2, 3]

In [ ]:
letters * 2 # repeats

['a', 'b', 'c', 'a', 'b', 'c']

In [88]:
# methods will change a list in place but do not return a value
rainbow = ['red', 'orange', 'yellow', 'green', 'blue']
rainbow

['red', 'orange', 'yellow', 'green', 'blue']

In [89]:
rainbow.append('purple') # the append method modified the rainbow. on its own, it doesn't return any value
rainbow

['red', 'orange', 'yellow', 'green', 'blue', 'purple']

In [90]:
rainbow.append(['purple'])
rainbow

['red', 'orange', 'yellow', 'green', 'blue', 'purple', ['purple']]

In [ ]:
# .extend() method  is used to add elements from an iterable to the end of a list
# add them one element at a time
rainbow.extend('violet') 
rainbow

['red',
 'orange',
 'yellow',
 'green',
 'blue',
 'purple',
 ['purple'],
 'v',
 'i',
 'o',
 'l',
 'e',
 't']

In [ ]:
# extend() will adds each element from another list individually
# But append() will add whole list to the end of current , BUT as single element
rainbow.extend(['purple', 'green'])
rainbow

['red',
 'orange',
 'yellow',
 'green',
 'blue',
 'purple',
 ['purple'],
 'v',
 'i',
 'o',
 'l',
 'e',
 't',
 'purple',
 'green']

In [ ]:
# how to insert items at a specific position/index
rainbow.insert(6, 'indigo')
rainbow

['red',
 'orange',
 'yellow',
 'green',
 'blue',
 'purple',
 'indigo',
 ['purple'],
 'v',
 'i',
 'o',
 'l',
 'e',
 't',
 'purple',
 'green']

In [ ]:
# remove
rainbow.remove('v')  # removed v element
rainbow

['red',
 'orange',
 'yellow',
 'green',
 'blue',
 'purple',
 'indigo',
 ['purple'],
 'i',
 'o',
 'l',
 'e',
 't',
 'purple',
 'green']

In [96]:
# clear a list
rainbow.clear()
rainbow


[]

In [97]:
# sorting list
fruit = ['pineapple', 'apple', 'kiwi', 'banana']
fruit


['pineapple', 'apple', 'kiwi', 'banana']

In [98]:
fruit.sort()
fruit

['apple', 'banana', 'kiwi', 'pineapple']

In [99]:
# sorted function
veggies = ['potato', 'tomato', 'salary', 'onion']
veggies

['potato', 'tomato', 'salary', 'onion']

In [ ]:
sorted(veggies) # since it is a function, it will return the results

['onion', 'potato', 'salary', 'tomato']

In [101]:
# tuple data type; use paranthesis () instead of []
# immutable, ordered (can ujse index to call individual elements)
mutable_synonyms = ('changeable', 'fluctuating', 'inconstant', 'variable')
mutable_synonyms

('changeable', 'fluctuating', 'inconstant', 'variable')

In [ ]:
# another way of defining tuples
also_empty = tuple()
also_empty

()

In [104]:
# another method
empty = ()
empty

()

In [106]:
mutable_synonyms + ('one more', 'another')


('changeable', 'fluctuating', 'inconstant', 'variable', 'one more', 'another')

In [107]:
mutable_synonyms # isn't changed since it is immutable

('changeable', 'fluctuating', 'inconstant', 'variable')

In [4]:
# set data type use {}
# it is mutable, unordered (elements do not maintain any specific order), distinct
# all elements are unique
things = {'coat', 'lock', 'books', 'apple', 'xylophone', 'lock', 'books'}
things # python removes the repeats and puts them in order

{'apple', 'books', 'coat', 'lock', 'xylophone'}

In [5]:
visitor_post_codes = ['m3r', 'm4t', 'm3d', 'm5p', 'm3r'] # a list that allows duplicates
visitor_post_codes

['m3r', 'm4t', 'm3d', 'm5p', 'm3r']

In [6]:
set(visitor_post_codes) # puts them in order and removes duplicates

{'m3d', 'm3r', 'm4t', 'm5p'}

In [7]:
# set operations
rainbow = {'red', 'yellow', 'green', 'blue'}
olympic_flag = {'green', 'yellow', 'black', 'blue'}


In [8]:
rainbow.difference(olympic_flag) # it will find values that are in the first but not the second set

{'red'}

In [9]:
olympic_flag.difference(rainbow)

{'black'}

In [10]:
# symmetric difference: find values that are only in one of the two sets
rainbow.symmetric_difference(olympic_flag)

{'black', 'red'}

In [11]:
rainbow.intersection(olympic_flag) # find the values that are common in the 2 sets

{'blue', 'green', 'yellow'}

In [12]:
# union: combine the 2 sets to get the unique values in both sets
rainbow.union(olympic_flag)

{'black', 'blue', 'green', 'red', 'yellow'}

# 2026-03-16 course

In [13]:
#tuples immutable (cannot be changed, unlike lists)
tuple_example = ('tree', 'plant', 'rock', 'forest')
tuple_example

('tree', 'plant', 'rock', 'forest')

In [ ]:
# sets {} are mutable and can be modified,allow no repeats (they are distinct)
forest_set = {'Tree', 'plant','rocks', 'creeks'}
forest_set

{'Tree', 'creeks', 'plant', 'rocks'}

In [ ]:
# Dictionaries {} data types: They are mutable, are ordered
# the have key value pairs key:value
# keys can be any immutable data types (strings, bools, numbers, tuples); values can be anything

capitals = {'Canada' : 'Otawa', 'US' : 'DC', 'Mexico' : 'Mexico city'}
capitals

{'Canada': 'Otawa', 'US': 'DC', 'Mexico': 'Mexico city'}

In [17]:
olympic_cities = {2020 : 'Tokyo', 2016: 'Rio de Janiro', 2012: 'London'}
olympic_cities

{2020: 'Tokyo', 2016: 'Rio de Janiro', 2012: 'London'}

In [18]:
# nest a dictionary within another dictionary

all_olympic_host = {'summer': olympic_cities,
                    'winter': {2022: 'Beijing', 2018: 'Pyeongchang'}}
all_olympic_host

{'summer': {2020: 'Tokyo', 2016: 'Rio de Janiro', 2012: 'London'},
 'winter': {2022: 'Beijing', 2018: 'Pyeongchang'}}

In [21]:
# E,pty dictionaries to be populated later on

empty_dictionary = {}
empty_dictionary

{}

In [24]:
empty_dic = dict()
empty_dic

{}

In [ ]:
# if we want a value for the key 2016 in the olympic_cities dictionary

# use the key as an index

olympic_cities[2016]

'Rio de Janiro'

In [26]:
all_olympic_host['summer']

{2020: 'Tokyo', 2016: 'Rio de Janiro', 2012: 'London'}

In [ ]:
# acessing the nested value within nested dictionary, call the keys from outside in in separate brakets

all_olympic_host['summer'][2016]

'Rio de Janiro'

value = my_dict.get(key, default=none)

 . key: the key whose value you want to retrieve
 . default (optional): the value to return if the key is not found in tthe dictionary. if not provided, it defaults to None

In [28]:
olympic_cities.get(2014)

In [29]:
# This method will provide back the string in the get()
olympic_cities.get(2004, 'Athens')

'Athens'

In [ ]:
# no value in the original olympic_cities dictionary
olympic_cities[2008]

KeyError: 2008

In [ ]:
# assigning the value for the 2008 key since it doesn;t exist

olympic_cities[2008] = 'Barcelona'

In [32]:
olympic_cities

{2020: 'Tokyo', 2016: 'Rio de Janiro', 2012: 'London', 2008: 'Barcelona'}

In [ ]:
# to update a value, simply enter a new value for the key

olympic_cities[2008] = 'Beijing'
olympic_cities

{2020: 'Tokyo', 2016: 'Rio de Janiro', 2012: 'London', 2008: 'Beijing'}

In [ ]:
# dictionaries are mutable since we have updated the values
# looking in all_olymic_cities dic that contains the olympic_cities
# we can see the value for 2008 is added

all_olympic_host


{'summer': {2020: 'Tokyo',
  2016: 'Rio de Janiro',
  2012: 'London',
  2008: 'Beijing'},
 'winter': {2022: 'Beijing', 2018: 'Pyeongchang'}}

In [ ]:
# del operator allown to remove key:value pairs
# here we delet the key:value for 2008

del olympic_cities[2020]
olympic_cities

{2016: 'Rio de Janiro', 2012: 'London', 2008: 'Beijing'}

In [36]:
# Dictionary methods

# using all_olympic_hosts

#.keys() returns all keys
all_olympic_host.keys()

dict_keys(['summer', 'winter'])

In [37]:
#.values will return all of the values

all_olympic_host.values()


dict_values([{2016: 'Rio de Janiro', 2012: 'London', 2008: 'Beijing'}, {2022: 'Beijing', 2018: 'Pyeongchang'}])

In [38]:
# .items() will return key.value pairs. 
# ie for nested dictionary
all_olympic_host['winter'].items()

dict_items([(2022, 'Beijing'), (2018, 'Pyeongchang')])

In [ ]:
# iteration: 
# for loop and while loop

# for loop

vowels = ['a', 'e', 'i', 'o', 'u']
for i in vowels:
    print(i)
    



a
e
i
o
u


In [40]:
for i in all_olympic_host:
    print(i)

summer
winter


In [48]:
veggies = ['carrot', 'tomato', 'potato']

for vegetable in veggies:
    if vegetable == 'tomato':
        veggies[1] = 'turnip'
    
    
print(veggies)

['carrot', 'turnip', 'potato']


In [ ]:
# range(n) function, creates an iterable that starts from 0 upto n-1

for i in range(7):
    print(i, i*2)

0 0
1 2
2 4
3 6
4 8
5 10
6 12


In [ ]:
input_files = ['data_01.csv', 'data_02.csv', 'data_03.csv', 'data_04.csv']

output_files =[]
for i in input_files:
    output_file_name = 'processed_' +i.replace('csv', 'xlsx') # create an output list in which the entries are created by concatenated processed_to data_,  
    output_files.append(output_file_name)  # replace the .csv to .xlsx and inserted into the output_files

output_files

['processed_data_01.xlsx',
 'processed_data_02.xlsx',
 'processed_data_03.xlsx',
 'processed_data_04.xlsx']

In [51]:
# in this example we knew the index of tomato was one. 


veggies = ['carrot', 'tomato', 'potato']

for vegetable in veggies:
    if vegetable == 'tomato':
        veggies[1] = 'turnip'
    
    
print(veggies)

['carrot', 'turnip', 'potato']


In [ ]:
# how to get back the index position of each item
# the enumerate() is used to iterated over a sequence (e.g list, tuple, string)
# while keeping track of the index position of each item


veggies = ['carrot', 'tomato', 'potato']

for idx,vegetable in enumerate(veggies): # for the 1st iteration, idx=0, and vegetable= 'carrot' : idx and vegetables are variables and anything can be used instead
    if vegetable == 'tomato':
        veggies[idx] = 'turnip'
# with iteration, 1 is added to idx and vegetable move one forward in the list
print(veggies)

['carrot', 'turnip', 'potato']


In [53]:
numbers = [1, 10, 100, 1000]
for idx, val in enumerate(numbers):
    numbers[idx] = val * 2

numbers

[2, 20, 200, 2000]

In [ ]:
# how to loop over 2 iterables that we can go over at the same time
# zip() allows us to loop over more than one datatypes at the same time

lats = (43, 56, 567, 23.5) #tuple
lons = (13.356, 2344.2, 34.7)

for i, j in zip(lats, lons):
    print(i, j)

43 13.356
56 2344.2
567 34.7


In [ ]:
# with for loops, we know how many times the loop runs
# While  loop continues until the condition is met

countdown = 4

while countdown > 0:
  print(countdown)
  countdown -= 1

4
3
2
1


In [ ]:
# be mindful of infinite loops
countdown = 4

while countdown > 0:
  print(countdown)
  countdown -= 1



4
3
2
1


In [ ]:
# break statement interrupts the execution of a loop

countdown = 4

while countdown > 0:
    print(countdown)
    if countdown == 3:
        print("we are breaking the loop early")
        break
    countdown -= 1
print('done iterating')

4
3
we are breaking the loop early
done iterating


In [ ]:
# it will continue repeating to ask for a password until 'open sesame' is entered
while True:
    password = input("What's the password")
    if password == "open sesame":
        print('you\'re in!')
        break

you're in!


In [71]:
# continue statement tells the python to leave the current iteration of the loop and starts back up at the top

wishes = 3

while wishes > 0:
    wish = input('Make a wish:')
    if wish == 'infinite wishes':
        print('you can\'t do that')
        continue
    else:
        print('wish granted')
    wishes -= 1
print('You have used all your wishes')

you can't do that
wish granted
wish granted
wish granted
You have used all your wishes


In [ ]:
# reading and writing files

# for open() function:
# 'r' : Read-only
# 'w' : Write. creates a new file if one doesn't exist. if the file exists, the current content are deleted and overwritten
# 'a' : Append: Adds to an existing file. If the file doesn;t exist, it will be created

# with ensures that the dile is properly closed after its suite (block of code) finishes exeution

# open(path of the file) return a file object, representation of the opened fie

# Read() methods:
# .read() return the full file contents
# .readline() return only the next line in the file and python will keep a track of where it is in the file
# .readlines() return the full file as a list and each item is one line in the file

with open(r"C:\Users\fermi\Desktop\history-git course.txt", 'r') as file: # r in the paranthesis converts it to raw text
    print(file.read())


  504  mkdir waffle
  505  cd waffle
  506  git init .
  507  ls -a
  508  nano dmytro.txt
  509  ls
  510  git status
  511  git add dmytro.txt 
  512  git status
  513  git commit -m "initial commit of notes about Dmytro"
  514  git status
  515  git log
  516  git branch
  517  git checkout -b development
  518  git branch
  519  nano dmytro.txt 
  520  git status
  521  git status
  522  git add .
  523  git commit -m "more notes about dmytro"
  524  git branch
  525  git log
  526  git checkout main
  527  git branch
  528  git log
  529  git checkout development
  530  git log
  531  git branch
  532  git log
  533  git checkout main
  534  git log
  535  git merge development
  536  git log
  537  ls
  538  nano anjali.txt
  539  ls
  540  git add anjali.txt 
  541  git commit -m "starting to say nice things about Anjali"
  542  git log
  543  git branch
  544  git checkout development
  545  git log
  546  ls
  547  git branch
  548  git merge main
  549  ls
  550  git branch
 

2026-03-18 Course

In [ ]:
with open(r"C:\Users\fermi\Desktop\history-git course.txt", 'r') as f: # f is just a name to call the file. anything can be used
    #print(f.readlines())
    #print(f.readlines())
    print(f.read())

  504  mkdir waffle
  505  cd waffle
  506  git init .
  507  ls -a
  508  nano dmytro.txt
  509  ls
  510  git status
  511  git add dmytro.txt 
  512  git status
  513  git commit -m "initial commit of notes about Dmytro"
  514  git status
  515  git log
  516  git branch
  517  git checkout -b development
  518  git branch
  519  nano dmytro.txt 
  520  git status
  521  git status
  522  git add .
  523  git commit -m "more notes about dmytro"
  524  git branch
  525  git log
  526  git checkout main
  527  git branch
  528  git log
  529  git checkout development
  530  git log
  531  git branch
  532  git log
  533  git checkout main
  534  git log
  535  git merge development
  536  git log
  537  ls
  538  nano anjali.txt
  539  ls
  540  git add anjali.txt 
  541  git commit -m "starting to say nice things about Anjali"
  542  git log
  543  git branch
  544  git checkout development
  545  git log
  546  ls
  547  git branch
  548  git merge main
  549  ls
  550  git branch
 

In [13]:
# writing file:
# .write() writes a string to a file
# .writelines() writes each item in an iterable to a file, with no separating text in between

provinces = ['BC', 'ON', 'AB', 'SK', 'Mb', 'QC', 'NL', 'NB', 'NS', 'PE']
with open("C:/Users/fermi/Desktop/provinces.txt", 'w') as province_file:
    province_file.writelines(provinces)

In [14]:
with open("C:/Users/fermi/Desktop/provinces.txt", 'r') as province_file:
    print(province_file.read())

BCONABSKMbQCNLNBNSPE


In [ ]:
import os # to get the working directory
os.getcwd()

'd:\\Repositories\\python'

In [21]:
os.listdir()

['.git',
 '.github',
 '.gitignore',
 '01_materials',
 '02_activities',
 '03_instructional_team',
 '04_this_cohort',
 '05_src',
 'LICENSE',
 'March 4.ipynb',
 'pyproject.toml',
 'Python-course.ipynb',
 'python-env',
 'README.md',
 'SETUP.md',
 'steps_to_ask_for_help.png',
 'uv.lock']

In [ ]:
# adding/appending the full paths of each item in the working directory one by one to the file full_paths list
cwd = os.getcwd()
full_paths = [] # full_paths initially is empty
for i in os.listdir():
    full_paths.append(os.path.join(cwd, i))

full_paths

['d:\\Repositories\\python\\.git',
 'd:\\Repositories\\python\\.github',
 'd:\\Repositories\\python\\.gitignore',
 'd:\\Repositories\\python\\01_materials',
 'd:\\Repositories\\python\\02_activities',
 'd:\\Repositories\\python\\03_instructional_team',
 'd:\\Repositories\\python\\04_this_cohort',
 'd:\\Repositories\\python\\05_src',
 'd:\\Repositories\\python\\LICENSE',
 'd:\\Repositories\\python\\March 4.ipynb',
 'd:\\Repositories\\python\\pyproject.toml',
 'd:\\Repositories\\python\\Python-course.ipynb',
 'd:\\Repositories\\python\\python-env',
 'd:\\Repositories\\python\\README.md',
 'd:\\Repositories\\python\\SETUP.md',
 'd:\\Repositories\\python\\steps_to_ask_for_help.png',
 'd:\\Repositories\\python\\uv.lock']

In [ ]:
text = 'Lavendar is a small purple fower'

if os.path.exists('plants.txt'):
    print('Plants.txt already exists')
else:
    with open('plants.txt', 'w') as f:
        f.write(text)

In [36]:
# class: blueprint or template for creating objects
# define the protperties (attributes) and behaviours (methods) that objects of that class will
# have user_defined datatypes

# object: specific instances of a class
# have properties (attributes)  and behaviours (methods)

# method: funtion that is associated with a calss and can be called on objects of that class
# behaviour of the objects

# attribute: pieces of data that belong to an object
# represent the state of the object


kcar_name = 'ketchup'   # these are all attributes
kcar_make = 'Volkswagen'
kcar_model = 'UP!'
kcar_colour = 'red'

dcar_name = 'Taylor'
dcar_make = 'Honda'
dcar_model = 'Civic'
dcar_colour = 'Black'

# we can define these attributes and more for anyones' car but it is cumbersome
# to avoide the time and make it simple, we define a class

# __init__ : 

class Car:
    def __init__(self, name, make, model, colour):
        self.name = name # methods
        self.make = make
        self.model = model
        self.colour = colour

    def honk(self):
        print('beep beep')

In [37]:
# now we use the defined class up

kcar = Car('Ketchup', 'VW', 'UP!', 'Red')
dcar = Car('Taylor', 'Honda', 'Civic', 'Black')

In [38]:
kcar.honk()

beep beep


In [29]:
kcar.colour

'Red'

In [30]:
dcar.make

'Honda'

In [ ]:
# class names start with the 1st character to be capital
# __init__ is a special method in python classes. it is automatically called when a new object of a class is created
# it initializes all of the object's attributes or properties
# self. is a references to the current instance of the class
# it is the first parameter in every method definition inside a class

class Person:
    def __init__(self, name, age): # every class starts with __innit__ method
        self.name  = name # self.name is assigned to name
        self.age = age

# self is an istance of the class, a referene to the object we are using
    
    def greet(self):
        print("Hello. My name is", self.name)
        

In [33]:
Fermisk = Person("Fermisk", 40)

In [34]:
Fermisk.name

'Fermisk'

In [35]:
Fermisk.greet()

Hello. My name is Fermisk


# NumPy library

In [43]:
# to import numpy to use

import numpy as np   # np is only an alias

In [ ]:
# first axis (rows) is 2 which is the number of blue brackets
# second axis (columns) is 3 and is the number of element inside the blue brackets
# a 2 x 3 arrays

a = np.array([[1, 2, 3], 
              [3, 2, 1]])   # each inside blue bracket is a row

a

array([[1, 2, 3],
       [3, 2, 1]])

In [45]:
# number f dimensions

a.ndim

2

In [ ]:
# shape (rows x columns)
a.shape

(2, 3)

In [ ]:
# number of elements which is the number of rows*coloumns (2*3=6)

a.size

6

In [ ]:
# every element inside the array should be the same as we see here there are all integeres
# in an array, we only hve whole numbers
# we also have a fixed size

a.dtype

dtype('int64')

In [ ]:
# to creat arrays with place holder contents such as zeros

np.zeros((2, 3, 2)) # creates a 2 x 3 x 2 array of zeros 

# 1st number: sets of blue brackets
# 2nd number: the number of elements within each blue bracket
# 3rd number:the second bracket from the outside (bigger and separate arrays)
# we can go up to n dimensions
# the outer bracket represents the entire array
# aaa = np.random.rand(3,4) to generate a randon array


array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [52]:
a

array([[1, 2, 3],
       [3, 2, 1]])

In [53]:
# creating an array of 1s
np.ones_like(a) # creating an array similar to a we created before but populate it with 1s

array([[1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.arange(1, 10, 2)  # an array aranged that goes upto 10 but in increments of 2

array([1, 3, 5, 7, 9])

In [56]:
np.arange(0, 1, 0.1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [ ]:
# generating a 3x4 array of random number from 1 to 10
# pink [aranthesis show we are inserting a tuple]
np.random.randint(1, 10, (3,4))

array([[5, 8, 7, 2],
       [9, 9, 5, 3],
       [2, 3, 2, 4]], dtype=int32)

In [ ]:
# if we want a set array of random numbers. the numbers won't change regardless of how many times it is run
# seed is the initial value of the numbers associated with the arra

np.random.seed(1) # the command is ran once and the random numbers generated will be set
np.random.randint(1, 10, (3, 4))

array([[6, 9, 6, 1],
       [1, 2, 8, 7],
       [3, 5, 6, 3]], dtype=int32)

In [67]:
np.random.seed(10) # the command is ran 10 times and the random numbers generated at the 10th time will be set
np.random.randint(1, 10, (3, 4))

array([[5, 1, 2, 1],
       [2, 9, 1, 9],
       [7, 5, 4, 1]], dtype=int32)

In [ ]:
np.repeat(10, 5) # one dimensional array in which 10 is repeated 5 times

array([10, 10, 10, 10, 10])

In [70]:
onedim_arr = np.array([1, 2, 3, 4, 5])
multidim_arr = np.repeat(onedim_arr, 5)
multidim_arr

array([1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5,
       5, 5, 5])

In [71]:
multidim_arr = np.tile(onedim_arr, [5, 1])
multidim_arr

array([[1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5]])

In [72]:
another_arr = np.tile(onedim_arr, (3, 3))
another_arr

array([[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5],
       [1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]])

In [ ]:
b = np.array([[5, 4, 3, 2, 1, 0], 
              [10, 8, 6, 4, 2, 0]])
b.T # T:transpose, all the rows become columns

array([[ 5, 10],
       [ 4,  8],
       [ 3,  6],
       [ 2,  4],
       [ 1,  2],
       [ 0,  0]])

In [74]:
b

array([[ 5,  4,  3,  2,  1,  0],
       [10,  8,  6,  4,  2,  0]])

In [ ]:
# reshaping the array.
# b is 6x2 (12 elements) thus the reshaped array shoud have the same number of ellements

b.reshape(4, 3) 

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0]])

In [76]:
# flatten the array into a 1D array

b.flatten()

array([ 5,  4,  3,  2,  1,  0, 10,  8,  6,  4,  2,  0])

In [ ]:
a # previous array

array([[1, 2, 3],
       [3, 2, 1]])

In [79]:
# to stack arrays in a horizontal axis
np.hstack([b, a])

array([[ 5,  4,  3,  2,  1,  0,  1,  2,  3],
       [10,  8,  6,  4,  2,  0,  3,  2,  1]])

In [ ]:
# to vertically stack arrays
np.vstack((b.reshape(4, 3), a))

# first reshape b to a 4 x 3 and then stack it on top of a 


array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0],
       [ 1,  2,  3],
       [ 3,  2,  1]])

In [84]:
b.reshape(4, 3)

array([[ 5,  4,  3],
       [ 2,  1,  0],
       [10,  8,  6],
       [ 4,  2,  0]])

In [86]:
# basic operations that are applied to vector

arr1 = np.array([5, 10, 15, 20])
arr1

array([ 5, 10, 15, 20])

In [88]:
arr2 = np.arange(5, 9)
arr2

array([5, 6, 7, 8])

In [89]:
arr1 - arr2

array([ 0,  4,  8, 12])

In [91]:
arr1

array([ 5, 10, 15, 20])

In [92]:
arr1 * 2

array([10, 20, 30, 40])

In [ ]:
arr2 # 1 x 4

array([5, 6, 7, 8])

In [ ]:
arr2 + np.array([1, 2]) # the added array is 1 x 2 and is different from arr2 thus cannot perform

ValueError: operands could not be broadcast together with shapes (4,) (2,) 

In [99]:
arr1

array([ 5, 10, 15, 20])

In [ ]:
print(arr1.max()) # max number in arr2

20


In [ ]:
print(arr1.mean()) # the mean of arr1

12.5


In [ ]:
print(np.median(arr1)) # median of arr1

12.5


In [ ]:
# operations in multiple dimentions

tens = np.arange(0, 120, 10).reshape(3, 4) # array from 0 upto 120 in 10 increments; then resape into 3x4 array
tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [102]:
horizontal = np.array([-5, -10, -15, -20])
horizontal

array([ -5, -10, -15, -20])

In [ ]:
tens + horizontal # adds each element of horizontal that is 1D to each row of tens in order

array([[-5,  0,  5, 10],
       [35, 40, 45, 50],
       [75, 80, 85, 90]])

In [105]:
vertical = np.array([[100], 
                    [200], 
                    [300]]) # a 3x1 vector
vertical

array([[100],
       [200],
       [300]])

In [ ]:
tens + vertical # adds each column of vertical to each column of tens vector in order of top to bottom

array([[100, 110, 120, 130],
       [240, 250, 260, 270],
       [380, 390, 400, 410]])

In [107]:
# we can apply methods to multidimensional arrays but we need to add axis
# axis = 0: column-wise opperation (going down the rows)
# axis = 1: row-wise operation (across the column)

tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [ ]:
tens.mean(axis=0) # 0 means columnwise. for each column, calculates the mean and returns it in a 1D

array([40., 50., 60., 70.])

In [109]:
tens.mean(axis=1)

array([15., 55., 95.])

In [ ]:
# indexing, slicing, iterating
# everything in python is indexed 0

arr1

array([ 5, 10, 15, 20])

In [ ]:
arr1[1] #slicing; getting back the value of item in position 2 (index starts from 0)

np.int64(10)

In [ ]:
arr1[1:3] # position 2 to 3

array([10, 15])

In [113]:
for i in arr1:
    print(i)

5
10
15
20


In [114]:
tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [ ]:
tens[1, 2] # row 2 column 3 (index starts at 0)

np.int64(60)

In [ ]:
tens[1] # all the columns at row 1 (second row)

array([40, 50, 60, 70])

In [ ]:
tens[:,0] # all th erows at 1st column

array([ 0, 40, 80])

In [119]:
tens

array([[  0,  10,  20,  30],
       [ 40,  50,  60,  70],
       [ 80,  90, 100, 110]])

In [ ]:
# for 3D (set, row, col)
tens[0:2, 1:3] # row 0 columns upto

array([[10, 20],
       [50, 60]])

In [121]:
matrix1 = np.random.randint(1, 11, 12).reshape(3, 4)
matrix2 = matrix1

# independent copy
matrix3 = matrix1.copy()
matrix1

array([[ 5,  7,  9,  2],
       [ 9,  5,  2,  4],
       [ 7,  6,  4, 10]], dtype=int32)

In [123]:
matrix1[1] = [0, 0, 0, 0]

In [ ]:
matrix1 # mtrix1 changed

array([[ 5,  7,  9,  2],
       [ 0,  0,  0,  0],
       [ 7,  6,  4, 10]], dtype=int32)

In [ ]:
matrix2 # matrix2 follows matrix1 and changes as matrix1 changes

array([[ 5,  7,  9,  2],
       [ 0,  0,  0,  0],
       [ 7,  6,  4, 10]], dtype=int32)

In [ ]:
matrix3 # matrix3 is an independent copy of matrix1 and won't change as matrix1 changes

array([[ 5,  7,  9,  2],
       [ 9,  5,  2,  4],
       [ 7,  6,  4, 10]], dtype=int32)